/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libreria;
import com.UBAM.Combos.Editoriales;
import com.UBAM.Combos.Generos;
import com.UBAM.Combos.Idiomas;
import com.UBAM.Combos.RellenarCombos;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;



import com.UBAM.ConnectionMySQL.ConnectionMySQL;
import com.mysql.jdbc.Connection;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author rogerconge
 */
public class Agregar extends javax.swing.JFrame {

    ConnectionMySQL conexion = new ConnectionMySQL();
    java.sql.Connection cn = conexion.abrirConexion();
    
    
    public Agregar(){
        initComponents();
        conexion.abrirConexion();

        cargarCombo(combo_idioma);
                cargarCombo1(combo_genero);
                cargarCombo2(combo_editorial);

    }

    
 
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nomlibro = new javax.swing.JTextField();
        combo_editorial = new javax.swing.JComboBox<>();
        combo_genero = new javax.swing.JComboBox<>();
        combo_idioma = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_coslibro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_canticopias = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Agregar Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 36))); // NOI18N

        combo_editorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_editorialActionPerformed(evt);
            }
        });

        combo_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_generoActionPerformed(evt);
            }
        });

        combo_idioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_idiomaActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione un Idioma--->");

        jLabel2.setText("Seleccione un genero--->");

        jLabel3.setText("Seleccione un editorial--->");

        jLabel4.setText("Nombre del Libro:");

        jLabel5.setText("Costo $ del libro:");

        jLabel6.setText("Cantidad de copias:");

        btn_agregar.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_salir.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btn_salir.setText("Regresar");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_nomlibro)
                        .addComponent(combo_editorial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combo_genero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combo_idioma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(45, 45, 45)
                .addComponent(btn_salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_agregar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(txt_coslibro)
                            .addComponent(txt_canticopias, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nomlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_coslibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_canticopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(combo_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_salir))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        dispose();
        Interfaz inter = new Interfaz();
        inter.setLocationRelativeTo(null);
        inter.setTitle("Menu");
        inter.setVisible(true);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void combo_editorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_editorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_editorialActionPerformed

    private void combo_idiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_idiomaActionPerformed

    }//GEN-LAST:event_combo_idiomaActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        String nombreLibro = txt_nomlibro.getText();
    String precioLibroStr = txt_coslibro.getText();
    String existenciasStr = txt_canticopias.getText();
    String activo = "1"; // Establece el valor por defecto para el campo activo

    if (nombreLibro.isEmpty() || precioLibroStr.isEmpty() || existenciasStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos");
        return;
    }

    try {
        int generoId = combo_genero.getSelectedIndex() + 1; // Index + 1 porque los IDs en la base de datos comienzan desde 1
        int editorialId = combo_editorial.getSelectedIndex() + 1; // Index + 1 porque los IDs en la base de datos comienzan desde 1
        int idiomaId = combo_idioma.getSelectedIndex() + 1; // Index + 1 porque los IDs en la base de datos comienzan desde 1
        int precioLibro = Integer.parseInt(precioLibroStr);
        int existencias = Integer.parseInt(existenciasStr);

        // Llamar al procedimiento almacenado para insertar el libro
        Connection con = null;
        CallableStatement cs = null;

        try {
            cn = conexion.abrirConexion();
            cs = cn.prepareCall("{call InsertarLibro(?, ?, ?, ?, ?, ?, ?)}");
            cs.setString(1, nombreLibro);
            cs.setInt(2, generoId);
            cs.setInt(3, editorialId);
            cs.setInt(4, idiomaId);
            cs.setInt(5, precioLibro);
            cs.setInt(6, existencias);
            cs.setString(7, activo);
            cs.execute();
            JOptionPane.showMessageDialog(this, "Libro insertado exitosamente");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al insertar el libro: " + e.getMessage());
        } finally {
            try {
                if (cs != null) {
                    cs.close();
                }
                if (cn != null) {
                    conexion.cerrarConexion();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al cerrar la conexión: " + e.getMessage());
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido para el precio y las existencias");
    }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void combo_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_generoActionPerformed

    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> combo_editorial;
    private javax.swing.JComboBox<String> combo_genero;
    private javax.swing.JComboBox<String> combo_idioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_canticopias;
    private javax.swing.JTextField txt_coslibro;
    private javax.swing.JTextField txt_nomlibro;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo(JComboBox c) {
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        c.setModel (combo);
        RellenarCombos lc = new RellenarCombos();
        try{
            Statement st = cn.createStatement();
            ResultSet rs=st.executeQuery("SELECT Idioma_Idioma FROM tbl_cat_idioma");
            while (rs.next()){
               Idiomas ido = new Idiomas();
               ido.setNombre_idioma(rs.getString(1));
               lc.Agregaridiomas(ido);
               combo.addElement(ido.getNombre_idioma());
                System.out.println("Exito...");
            }
        }catch (Exception e){
            System.out.println("ERROR, FALLO EL COMBO"+e);
            
        }
    }
    
       private void cargarCombo1(JComboBox c) {
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        c.setModel (combo);
        RellenarCombos lc = new RellenarCombos();
        try{
            Statement st = cn.createStatement();
            ResultSet rs=st.executeQuery("SELECT Genero_Genero FROM tbl_cat_genero");
            while (rs.next()){
               Generos ido = new Generos();
               ido.setNombre_genero(rs.getString(1));
               lc.Agregargeneros(ido);
               combo.addElement(ido.getNombre_genero());
                System.out.println("Exito...");
            }
        }catch (Exception e){
            System.out.println("ERROR, FALLO EL COMBO"+e);
            
        }
    }
       
       
           private void cargarCombo2(JComboBox c) {
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        c.setModel (combo);
        RellenarCombos lc = new RellenarCombos();
        try{
            Statement st = cn.createStatement();
            ResultSet rs=st.executeQuery("SELECT Editorial_Editorial FROM tbl_cat_editorial");
            while (rs.next()){
               Editoriales ido = new Editoriales();
               ido.setNombre_editorial(rs.getString(1));
               lc.Agregareditorial(ido);
               combo.addElement(ido.getNombre_editorial());
                System.out.println("Exito...");
            }
        }catch (Exception e){
            System.out.println("ERROR, FALLO EL COMBO"+e);
            
        }
    }
       
    
}
